name: Ensure Manifest Approval

on:
  push:
    branches:
      - main # or your target branch
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  update-baseline:
    name: Update Baseline Manifest
    needs: require-approval
    if: github.ref == 'refs/heads/main'  # Run only on push to main (after merge)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download manifest-diff artifact
        uses: actions/download-artifact@v3
        with:
          name: manifest-diff

      - name: Check for Manifest Diff
        id: check_diff
        run: |
          if [ -s manifest-diff.txt ]; then
            echo "diff_exists=true" >> $GITHUB_OUTPUT
          else
            echo "diff_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Baseline Manifest
        if: steps.check_diff.outputs.diff_exists == 'true'  # Check if diff exists
        run: |
          # Apply the diff to the baseline manifest
          patch baseline_AndroidManifest.xml < manifest-diff.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add baseline_AndroidManifest.xml
          git commit -m "Update baseline AndroidManifest.xml"
          git push
